---
tasks:
  - name: Tailscale Install Signing Key
    ansible.builtin.get_url:
      url: https://pkgs.tailscale.com/stable/{{ansible_distribution|lower}}/{{ansible_distribution_release|lower}}.noarmor.gpg
      dest: /usr/share/keyrings/tailscale-archive-keyring.gpg

  - name: Tailscale apt source
    ansible.builtin.apt_repository:
      repo: "deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/{{ansible_distribution|lower}} {{ansible_distribution_release|lower}} main"
      state: present
    notify: 
      - Update repositories cache

  - name: Run Handler to update apt cache, if required
    ansible.builtin.meta: flush_handlers

  - name: Install "tailscale" package
    ansible.builtin.apt:
      name: tailscale

handlers:
  - name: Update repositories cache
    ansible.builtin.apt:
      update_cache: yes
